{
  try {
    while (!killRunnable && iterator.hasNext()) {
      try {
        back.acquire();
        queue.put(iterator.next());
      }
  finally {
        back.release();
      }
    }
  }
 catch (  InterruptedException e) {
    if (killRunnable) {
      return;
    }
 else     exception=new RuntimeException("Runnable interrupted unexpectedly",e);
  }
catch (  RuntimeException e) {
    exception=e;
  }
 finally {
    isAlive=false;
    runCompletedSemaphore.release();
  }
}
